/* payment 테이블 변경 전체 선택 후 실행 해 주세요 */

ALTER TABLE payment MODIFY payment_bookdate DEFAULT (null);
ALTER TABLE payment MODIFY payment_bookdate varchar2(300);
ALTER TABLE payment MODIFY payment_bookdate DEFAULT (null);

ALTER TABLE PAYMENT DROP CONSTRAINT FK_ACTIVITY_TO_PAYMENT;
ALTER TABLE PAYMENT DROP CONSTRAINT FK_FLIGHT_TO_PAYMENT;
ALTER TABLE PAYMENT DROP CONSTRAINT FK_HOTEL_TO_PAYMENT;
ALTER TABLE PAYMENT DROP CONSTRAINT FK_LANTRIP_TO_PAYMENT;
ALTER TABLE PAYMENT DROP CONSTRAINT FK_MEMBERS_TO_PAYMENT;

ALTER TABLE payment ADD flight_title VARCHAR2(600);
ALTER TABLE payment ADD hotel_title VARCHAR2(600);
ALTER TABLE payment ADD activity_title VARCHAR2(600);
ALTER TABLE payment ADD lantrip_title VARCHAR2(600);
ALTER TABLE payment ADD product_category VARCHAR2(600);

commit